version: '3.8'

services:

  flask:
    container_name: flask
    build:
      context: .
    ports:
      - 5000:5000
    env_file: .env
    networks:
      - fmsb-network
    volumes:
      - .:/code


networks:
  default:
    driver: bridge
  fmsb-network:
    external: true


volumes:
  data: