version: '3'
services:
  
  elasticsearch:
    container_name: elasticsearch 
    image: elasticsearch:7.0.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - fmsb-network

  kibana:
    container_name: kibana
    image: kibana:7.0.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - fmsb-network

networks:
  default:
    driver: bridge
  fmsb-network:
    external: true


volumes:
  data: